-- black-metal.lua — matches Ghostty "black metal" theme
-- bg=#000000 fg=#c1c1c1 teal=#486e6f pink=#dd9999 red=#a06666

vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.background = "dark"
vim.g.colors_name = "black-metal"

local c = {
  bg     = "#000000",
  bg1    = "#0a0a0a",
  bg2    = "#111111",
  bg3    = "#1a1a1a",
  dark   = "#404040",
  gray1  = "#555555",
  gray2  = "#666666",
  gray3  = "#888888",
  gray4  = "#999999",
  gray5  = "#aaaaaa",
  fg     = "#c1c1c1",
  teal   = "#486e6f",
  pink   = "#dd9999",
  red    = "#a06666",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Editor
hi("Normal",            { fg = c.fg,    bg = c.bg })
hi("NormalNC",          { fg = c.fg,    bg = c.bg })
hi("NormalFloat",       { fg = c.fg,    bg = c.bg1 })
hi("FloatBorder",       { fg = c.dark,  bg = c.bg1 })
hi("FloatTitle",        { fg = c.gray4, bg = c.bg1, bold = true })
hi("Cursor",            { fg = c.bg,    bg = c.fg })
hi("CursorIM",          { fg = c.bg,    bg = c.fg })
hi("CursorLine",        { bg = c.bg1 })
hi("CursorColumn",      { bg = c.bg1 })
hi("CursorLineNr",      { fg = c.gray4 })
hi("LineNr",            { fg = c.dark })
hi("SignColumn",        { fg = c.dark,  bg = c.bg })
hi("ColorColumn",       { bg = c.bg1 })
hi("VertSplit",         { fg = c.dark,  bg = c.bg })
hi("WinSeparator",      { fg = c.dark,  bg = c.bg })
hi("StatusLine",        { fg = c.gray4, bg = c.bg1 })
hi("StatusLineNC",      { fg = c.dark,  bg = c.bg })
hi("TabLine",           { fg = c.gray3, bg = c.bg1 })
hi("TabLineFill",       { bg = c.bg })
hi("TabLineSel",        { fg = c.fg,    bg = c.bg3, bold = true })
hi("Visual",            { bg = "#1e1e1e" })
hi("VisualNOS",         { bg = "#1e1e1e" })
hi("Search",            { fg = c.bg,    bg = c.teal })
hi("IncSearch",         { fg = c.bg,    bg = c.pink })
hi("CurSearch",         { fg = c.bg,    bg = c.pink })
hi("Pmenu",             { fg = c.fg,    bg = c.bg1 })
hi("PmenuSel",          { fg = c.fg,    bg = c.bg3, bold = true })
hi("PmenuSbar",         { bg = c.bg2 })
hi("PmenuThumb",        { bg = c.dark })
hi("PmenuMatch",        { fg = c.pink })
hi("PmenuMatchSel",     { fg = c.pink,  bg = c.bg3, bold = true })
hi("Folded",            { fg = c.gray2, bg = c.bg1 })
hi("FoldColumn",        { fg = c.dark,  bg = c.bg })
hi("DiffAdd",           { bg = "#061006" })
hi("DiffChange",        { bg = "#080810" })
hi("DiffDelete",        { fg = c.dark,  bg = "#100606" })
hi("DiffText",          { bg = "#0f0f20" })
hi("MatchParen",        { fg = c.pink,  bold = true })
hi("NonText",           { fg = c.dark })
hi("SpecialKey",        { fg = c.dark })
hi("Whitespace",        { fg = c.dark })
hi("EndOfBuffer",       { fg = c.bg })
hi("ErrorMsg",          { fg = c.pink })
hi("WarningMsg",        { fg = c.red })
hi("ModeMsg",           { fg = c.gray4 })
hi("MoreMsg",           { fg = c.teal })
hi("Question",          { fg = c.teal })
hi("WildMenu",          { fg = c.fg,    bg = c.bg3 })
hi("Title",             { fg = c.fg,    bold = true })
hi("Directory",         { fg = c.teal })
hi("QuickFixLine",      { bg = c.bg3 })
hi("Conceal",           { fg = c.gray2 })
hi("SpellBad",          { undercurl = true, sp = c.pink })
hi("SpellCap",          { undercurl = true, sp = c.red })
hi("SpellRare",         { undercurl = true, sp = c.teal })
hi("SpellLocal",        { undercurl = true, sp = c.gray4 })

-- Syntax
hi("Comment",           { fg = c.gray2, italic = true })
hi("Constant",          { fg = c.pink })
hi("String",            { fg = c.pink })
hi("Character",         { fg = c.pink })
hi("Number",            { fg = c.gray5 })
hi("Boolean",           { fg = c.teal })
hi("Float",             { fg = c.gray5 })
hi("Identifier",        { fg = c.fg })
hi("Function",          { fg = c.gray5 })
hi("Statement",         { fg = c.teal })
hi("Keyword",           { fg = c.teal })
hi("Conditional",       { fg = c.teal })
hi("Repeat",            { fg = c.teal })
hi("Label",             { fg = c.teal })
hi("Operator",          { fg = c.gray4 })
hi("Exception",         { fg = c.red })
hi("PreProc",           { fg = c.gray4 })
hi("Include",           { fg = c.gray4 })
hi("Define",            { fg = c.gray4 })
hi("Macro",             { fg = c.gray4 })
hi("PreCondit",         { fg = c.gray4 })
hi("Type",              { fg = c.gray5 })
hi("StorageClass",      { fg = c.teal })
hi("Structure",         { fg = c.teal })
hi("Typedef",           { fg = c.teal })
hi("Special",           { fg = c.gray5 })
hi("SpecialChar",       { fg = c.pink })
hi("Tag",               { fg = c.teal })
hi("Delimiter",         { fg = c.gray3 })
hi("SpecialComment",    { fg = c.gray3, italic = true })
hi("Debug",             { fg = c.red })
hi("Underlined",        { underline = true })
hi("Bold",              { bold = true })
hi("Italic",            { italic = true })
hi("Ignore",            { fg = c.dark })
hi("Error",             { fg = c.pink, bold = true })
hi("Todo",              { fg = c.bg,   bg = c.teal, bold = true })

-- Treesitter
hi("@comment",                  { link = "Comment" })
hi("@comment.documentation",    { fg = c.gray3, italic = true })
hi("@keyword",                  { fg = c.teal })
hi("@keyword.import",           { fg = c.gray4 })
hi("@keyword.function",         { fg = c.teal })
hi("@keyword.return",           { fg = c.teal })
hi("@keyword.operator",         { fg = c.teal })
hi("@keyword.conditional",      { fg = c.teal })
hi("@keyword.repeat",           { fg = c.teal })
hi("@keyword.exception",        { fg = c.red })
hi("@function",                 { fg = c.gray5 })
hi("@function.builtin",         { fg = c.gray4 })
hi("@function.call",            { fg = c.fg })
hi("@function.method",          { fg = c.gray5 })
hi("@function.method.call",     { fg = c.fg })
hi("@variable",                 { fg = c.fg })
hi("@variable.builtin",         { fg = c.teal })
hi("@variable.parameter",       { fg = c.gray5 })
hi("@variable.member",          { fg = c.fg })
hi("@type",                     { fg = c.gray5 })
hi("@type.builtin",             { fg = c.teal })
hi("@type.definition",          { fg = c.gray5 })
hi("@string",                   { fg = c.pink })
hi("@string.escape",            { fg = c.red })
hi("@string.special",           { fg = c.red })
hi("@string.special.url",       { fg = c.teal, underline = true })
hi("@number",                   { fg = c.gray5 })
hi("@number.float",             { fg = c.gray5 })
hi("@boolean",                  { fg = c.teal })
hi("@constant",                 { fg = c.gray5 })
hi("@constant.builtin",         { fg = c.teal })
hi("@constant.macro",           { fg = c.gray4 })
hi("@operator",                 { fg = c.gray4 })
hi("@punctuation.delimiter",    { fg = c.gray3 })
hi("@punctuation.bracket",      { fg = c.gray4 })
hi("@punctuation.special",      { fg = c.gray4 })
hi("@tag",                      { fg = c.teal })
hi("@tag.attribute",            { fg = c.gray4 })
hi("@tag.delimiter",            { fg = c.gray3 })
hi("@markup.heading",           { fg = c.fg,   bold = true })
hi("@markup.heading.1",         { fg = c.fg,   bold = true })
hi("@markup.heading.2",         { fg = c.gray5,bold = true })
hi("@markup.heading.3",         { fg = c.gray4,bold = true })
hi("@markup.strong",            { bold = true })
hi("@markup.italic",            { italic = true })
hi("@markup.underline",         { underline = true })
hi("@markup.strikethrough",     { strikethrough = true })
hi("@markup.link",              { fg = c.teal, underline = true })
hi("@markup.link.url",          { fg = c.teal })
hi("@markup.raw",               { fg = c.pink })
hi("@markup.list",              { fg = c.gray4 })
hi("@markup.list.checked",      { fg = c.teal })
hi("@markup.list.unchecked",    { fg = c.gray3 })
hi("@module",                   { fg = c.fg })
hi("@namespace",                { fg = c.gray4 })
hi("@attribute",                { fg = c.gray4 })
hi("@constructor",              { fg = c.gray5 })
hi("@property",                 { fg = c.fg })

-- LSP semantic tokens
hi("@lsp.type.class",           { link = "@type" })
hi("@lsp.type.decorator",       { link = "@attribute" })
hi("@lsp.type.enum",            { link = "@type" })
hi("@lsp.type.enumMember",      { link = "@constant" })
hi("@lsp.type.function",        { link = "@function" })
hi("@lsp.type.interface",       { link = "@type" })
hi("@lsp.type.macro",           { link = "@constant.macro" })
hi("@lsp.type.method",          { link = "@function.method" })
hi("@lsp.type.namespace",       { link = "@namespace" })
hi("@lsp.type.parameter",       { link = "@variable.parameter" })
hi("@lsp.type.property",        { link = "@property" })
hi("@lsp.type.struct",          { link = "@type" })
hi("@lsp.type.type",            { link = "@type" })
hi("@lsp.type.typeParameter",   { link = "@type" })
hi("@lsp.type.variable",        { link = "@variable" })
hi("@lsp.mod.deprecated",       { strikethrough = true })

-- Diagnostics
hi("DiagnosticError",               { fg = c.pink })
hi("DiagnosticWarn",                { fg = c.red })
hi("DiagnosticInfo",                { fg = c.teal })
hi("DiagnosticHint",                { fg = c.gray4 })
hi("DiagnosticOk",                  { fg = c.teal })
hi("DiagnosticVirtualTextError",    { fg = c.red,   bg = "#120606", italic = true })
hi("DiagnosticVirtualTextWarn",     { fg = c.red,   bg = "#100d06", italic = true })
hi("DiagnosticVirtualTextInfo",     { fg = c.teal,  bg = "#050c0c", italic = true })
hi("DiagnosticVirtualTextHint",     { fg = c.gray2, bg = c.bg1,    italic = true })
hi("DiagnosticUnderlineError",      { undercurl = true, sp = c.pink })
hi("DiagnosticUnderlineWarn",       { undercurl = true, sp = c.red })
hi("DiagnosticUnderlineInfo",       { undercurl = true, sp = c.teal })
hi("DiagnosticUnderlineHint",       { undercurl = true, sp = c.gray3 })
hi("DiagnosticDeprecated",          { strikethrough = true, sp = c.gray3 })
hi("LspReferenceText",              { bg = c.bg3 })
hi("LspReferenceRead",              { bg = c.bg3 })
hi("LspReferenceWrite",             { bg = c.bg3, bold = true })
hi("LspInlayHint",                  { fg = c.gray2, bg = c.bg1, italic = true })
hi("LspCodeLens",                   { fg = c.gray2, italic = true })

-- GitSigns
hi("GitSignsAdd",                   { fg = c.teal })
hi("GitSignsChange",                { fg = c.gray4 })
hi("GitSignsDelete",                { fg = c.red })
hi("GitSignsAddNr",                 { fg = c.teal })
hi("GitSignsChangeNr",              { fg = c.gray4 })
hi("GitSignsDeleteNr",              { fg = c.red })
hi("GitSignsAddLn",                 { bg = "#061006" })
hi("GitSignsChangeLn",              { bg = "#080810" })

-- Telescope
hi("TelescopeNormal",               { fg = c.fg,    bg = c.bg })
hi("TelescopeBorder",               { fg = c.dark,  bg = c.bg })
hi("TelescopePromptNormal",         { fg = c.fg,    bg = c.bg1 })
hi("TelescopePromptBorder",         { fg = c.dark,  bg = c.bg1 })
hi("TelescopePromptTitle",          { fg = c.teal,  bg = c.bg1, bold = true })
hi("TelescopePromptPrefix",         { fg = c.teal,  bg = c.bg1 })
hi("TelescopeResultsNormal",        { fg = c.fg,    bg = c.bg })
hi("TelescopeResultsBorder",        { fg = c.dark,  bg = c.bg })
hi("TelescopeResultsTitle",         { fg = c.gray4, bg = c.bg })
hi("TelescopePreviewNormal",        { fg = c.fg,    bg = c.bg })
hi("TelescopePreviewBorder",        { fg = c.dark,  bg = c.bg })
hi("TelescopePreviewTitle",         { fg = c.gray4, bg = c.bg })
hi("TelescopeSelection",            { bg = c.bg3 })
hi("TelescopeSelectionCaret",       { fg = c.teal,  bg = c.bg3 })
hi("TelescopeMatching",             { fg = c.pink,  bold = true })
hi("TelescopeMultiSelection",       { fg = c.teal })

-- fzf-lua
hi("FzfLuaNormal",                  { link = "TelescopeNormal" })
hi("FzfLuaBorder",                  { link = "TelescopeBorder" })
hi("FzfLuaTitle",                   { fg = c.teal,  bold = true })
hi("FzfLuaFzfMatch",                { fg = c.pink,  bold = true })
hi("FzfLuaFzfCursorLine",           { bg = c.bg3 })

-- nvim-tree
hi("NvimTreeNormal",                { fg = c.fg,    bg = c.bg })
hi("NvimTreeNormalNC",              { fg = c.fg,    bg = c.bg })
hi("NvimTreeFolderIcon",            { fg = c.teal })
hi("NvimTreeOpenedFolderIcon",      { fg = c.pink })
hi("NvimTreeFolderName",            { fg = c.fg })
hi("NvimTreeOpenedFolderName",      { fg = c.fg })
hi("NvimTreeRootFolder",            { fg = c.gray4, bold = true })
hi("NvimTreeGitDirty",              { fg = c.red })
hi("NvimTreeGitStaged",             { fg = c.teal })
hi("NvimTreeGitNew",                { fg = c.teal })
hi("NvimTreeGitDeleted",            { fg = c.red })
hi("NvimTreeSpecialFile",           { fg = c.pink })
hi("NvimTreeIndentMarker",          { fg = c.dark })
hi("NvimTreeWinSeparator",          { fg = c.dark,  bg = c.bg })

-- which-key
hi("WhichKey",                      { fg = c.teal })
hi("WhichKeyGroup",                 { fg = c.gray5, bold = true })
hi("WhichKeyDesc",                  { fg = c.fg })
hi("WhichKeySeparator",             { fg = c.dark })
hi("WhichKeyFloat",                 { bg = c.bg1 })
hi("WhichKeyBorder",                { fg = c.dark,  bg = c.bg1 })

-- indent-blankline
hi("IblIndent",                     { fg = c.bg2 })
hi("IblScope",                      { fg = c.dark })

-- mini.indentscope
hi("MiniIndentscopeSymbol",         { fg = c.dark })

-- Noice
hi("NoiceCmdline",                  { fg = c.fg,    bg = c.bg1 })
hi("NoiceCmdlineIcon",              { fg = c.teal })
hi("NoiceCmdlinePopup",             { fg = c.fg,    bg = c.bg1 })
hi("NoiceCmdlinePopupBorder",       { fg = c.dark,  bg = c.bg1 })
hi("NoicePopup",                    { fg = c.fg,    bg = c.bg1 })
hi("NoicePopupBorder",              { fg = c.dark,  bg = c.bg1 })
hi("NoiceConfirm",                  { fg = c.fg,    bg = c.bg1 })
hi("NoiceConfirmBorder",            { fg = c.teal,  bg = c.bg1 })

-- lualine handled by lualine config, but set base
hi("lualine_a_normal",              { fg = c.bg,    bg = c.teal, bold = true })
hi("lualine_b_normal",              { fg = c.fg,    bg = c.bg2 })
hi("lualine_c_normal",              { fg = c.gray4, bg = c.bg1 })
